### ISSUE TITLE
File, Elva.exe.manifest, has a different computed hash than specified in the manifest

### ISSUE THREAD

**Issue by jjonescz** [TypNull/Elva#1]
Responding to your comment under [my blog post](https://janjones.me/posts/clickonce-installer-build-publish-github/) here.

I briefly looked and don't understand why the error occurs. The manifest contains a hash for the exe file:

https://github.com/TypNull/Elva/blob/b9bd4774a6ba2e984617038d68622212a2d88fd7/Application%20Files/Elva_0_1_1_0/Elva.dll.manifest#L108

and it matches the hash of the exe file when I download it and compute its SHA25 hash (the hash in the manifest is Base64-encoded, I [converted it to hex](https://base64.guru/converter/decode/hex) to compare with SHA256 that I got), so I don't see why the error complains that the hash is different.

When you run the script locally, does it produce different files? For example, are there any differences in the `Elva.dll.manifest` file?

Other than that, I guess you can ask at ClickOnce GitHub repo: https://github.com/dotnet/deployment-tools

**Comment by TypNull** [comment]
I appreciate your quick reply.

I followed your instructions and compared the files. The hash code is different, but I think that's normal when I build them again. However, on GitHub pages, there is an extra section for the file `lottie_sharp.ico` that contains the hash information, such as this:

```
<file name="lottie_sharp.ico" size="305805">
    <hash>
      <dsig:Transforms>
        <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
      </dsig:Transforms>
      <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256" />
      <dsig:DigestValue>/M85lUnP5gKQ7+QKaTkZO2O2GNVYqFVDzfC9xw7zhg4=</dsig:DigestValue>
    </hash>
</file>
```

This section is not present in the local version. Also, the size of the `Elva.exe` file is different: locally it is `155136` bytes, but on GitHub it is `155136` bytes. Other than that, there are no differences in the files that are produced.

**Comment by jjonescz** [comment]
> locally it is `155136` bytes, but on GitHub it is `155136` bytes.

These numbers look the same; you probably copy-pasted the same one :)

**Comment by jjonescz** [comment]
Anyway, that might indicate there's something weird going on with the exe file. Maybe something with signing. Try also searching the web for "has a different computed hash than specified in the manifest" if you see something that might look related to your project (I don't know your project architecture, so I might've missed something obvious). As a last resort I guess you could try to simplify / remove parts of the project until you get to a blank project (which should work) and on the way you should find which part causes the problem :)

**Comment by jjonescz** [comment]
> However, on GitHub pages, there is an extra section for the file `lottie_sharp.ico` that contains the hash information
> This section is not present in the local version.

This is also suspicious, might be the problem; try removing the icon completely to verify.

**Comment by TypNull** [comment]
> > locally it is `155136` bytes, but on GitHub it is `155136` bytes.
> 
> These numbers look the same; you probably copy-pasted the same one :)

What I meant was that the version on GitHub is 157184 bytes in size.
I have looked online for a solution to my issue, but none of them seem to apply to my case. I thought it might be related to a bug in Visual Studio or MSBuild 17.7, but the logs show that it was built with 17.8. I also came across [this ](https://github.com/girimonti/TMG-Working-Group/issues/2#issuecomment-920984275)comment on GitHub, but since it works for you, I doubt that’s the cause.
I will try to remove parts and see what happens. Remove the `lottie_sharp.ico` and some other things to downgrade the .Net Version.

**Comment by TypNull** [comment]
Alright, I’ve recently created a new repository to experiment with the project. However, I realized that I forgot to include the dot from `.gitattributes`. Consequently, GitHub tampered with my line endings, leading to the issue. 
It was quite a silly oversight, but thankfully, I’ve identified it. 
Thank you for your fast and great support!
